name: 'coverage'
on:
  pull_request:
    branches:
      - master
      - main
jobs:
  coverage:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node: ['16.x']
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node }}
      - run: yarn install
      - uses: ArtiomTr/jest-coverage-report-action@v2.0-rc.6
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          threshold: 80
          package-manager: yarn
          annotations: none
          test-script: npx tsdx test --passWithNoTests --ci --coverage --coverageReporters="text" --coverageReporters="text-summary"
